### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by efik** [CodersCommunity/awesome-links#1]
Spis ważnych linków, tak aby dawać na forum linka do tego repo. Gdzie wszystko będzie w 1 miejscu. Np dla kategorii PHP link do awesome-php itd..
- [ ] Dodać plik CONTRIBUTING.md z info o PR itd..
- [ ] Dodać kategorie odpowiednie  
- [ ] FAQ najczęstszych pytań?  Czy nowe repo?
